### ISSUE TITLE
Experiments limited to 30 minutes

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#240]
The default timeout of RabbitMQ is 30 minutes. Hence, those messages corresponding to experiments lasting for more than 30 minutes are kept in the queue, provoking undesired restarts and mixes of results.

The workaround is to create an external config file for RabbitMQ to extend the timeout and attach this file using the docker-compose file.

rabbit-myconfig.conf:
```
# 100 hours in milliseconds to limit experiments
consumer_timeout = 3600000000
```

docker-compose.yml:
```
# https://docs.docker.com/compose/compose-file/
version: '3.2'
services:
  db:
    image: postgres:12-bullseye
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: "01234"
      POSTGRES_DB: "webge"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - backend

  gramev:
    image: jmcolmenar/webge
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8182:8182"
      - "5005:5005"
      - "9010:9010"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_DATASOURCE_USERNAME: "usuario"
      SPRING_DATASOURCE_PASSWORD: "01234"
      SPRING_FLYWAY_URL: "jdbc:postgresql://db:5432/webge"
      SPRING_FLYWAY_USER: "usuario"
      SPRING_FLYWAY_PASSWORD: "01234"
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_LISTENER_SIMPLE_CONCURRENCY: "16"
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:management
    volumes: 
      - ./rabbit-myconfig.conf:/etc/rabbitmq/conf.d/myconfig.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
volumes:
  pgdata2:

networks:
  backend:
```
